// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops
{
    public static class GetClusterStatus
    {
        /// <summary>
        /// ## # kops.getClusterStatus
        /// 
        /// Provides a kOps cluster status data source.
        /// 
        /// This data source assumes the cluster has been applied (or updated) see [kops.ClusterUpdater](https://www.terraform.io/docs/resources/cluster_updater).
        /// </summary>
        public static Task<GetClusterStatusResult> InvokeAsync(GetClusterStatusArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetClusterStatusResult>("kops:index/getClusterStatus:getClusterStatus", args ?? new GetClusterStatusArgs(), options.WithDefaults());

        /// <summary>
        /// ## # kops.getClusterStatus
        /// 
        /// Provides a kOps cluster status data source.
        /// 
        /// This data source assumes the cluster has been applied (or updated) see [kops.ClusterUpdater](https://www.terraform.io/docs/resources/cluster_updater).
        /// </summary>
        public static Output<GetClusterStatusResult> Invoke(GetClusterStatusInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetClusterStatusResult>("kops:index/getClusterStatus:getClusterStatus", args ?? new GetClusterStatusInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetClusterStatusArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// - String - ClusterName defines the target cluster name.
        /// </summary>
        [Input("clusterName", required: true)]
        public string ClusterName { get; set; } = null!;

        public GetClusterStatusArgs()
        {
        }
        public static new GetClusterStatusArgs Empty => new GetClusterStatusArgs();
    }

    public sealed class GetClusterStatusInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// - String - ClusterName defines the target cluster name.
        /// </summary>
        [Input("clusterName", required: true)]
        public Input<string> ClusterName { get; set; } = null!;

        public GetClusterStatusInvokeArgs()
        {
        }
        public static new GetClusterStatusInvokeArgs Empty => new GetClusterStatusInvokeArgs();
    }


    [OutputType]
    public sealed class GetClusterStatusResult
    {
        public readonly string ClusterName;
        public readonly bool Exists;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> InstanceGroups;
        public readonly bool IsValid;
        public readonly bool NeedsUpdate;

        [OutputConstructor]
        private GetClusterStatusResult(
            string clusterName,

            bool exists,

            string id,

            ImmutableArray<string> instanceGroups,

            bool isValid,

            bool needsUpdate)
        {
            ClusterName = clusterName;
            Exists = exists;
            Id = id;
            InstanceGroups = instanceGroups;
            IsValid = isValid;
            NeedsUpdate = needsUpdate;
        }
    }
}
