// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func GetAws(ctx *pulumi.Context) string {
	return config.Get(ctx, "kops:aws")
}
func GetFeatureFlags(ctx *pulumi.Context) string {
	return config.Get(ctx, "kops:featureFlags")
}
func GetKlog(ctx *pulumi.Context) string {
	return config.Get(ctx, "kops:klog")
}
func GetMock(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "kops:mock")
}
func GetOpenstack(ctx *pulumi.Context) string {
	return config.Get(ctx, "kops:openstack")
}
func GetStateStore(ctx *pulumi.Context) string {
	return config.Get(ctx, "kops:stateStore")
}
