// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class ClusterCloudProviderOpenstackBlockStorage
    {
        public readonly bool? CreateStorageClass;
        public readonly string? CsiPluginImage;
        public readonly bool? CsiTopologySupport;
        public readonly bool? IgnoreAz;
        public readonly string? OverrideAz;
        public readonly string? Version;

        [OutputConstructor]
        private ClusterCloudProviderOpenstackBlockStorage(
            bool? createStorageClass,

            string? csiPluginImage,

            bool? csiTopologySupport,

            bool? ignoreAz,

            string? overrideAz,

            string? version)
        {
            CreateStorageClass = createStorageClass;
            CsiPluginImage = csiPluginImage;
            CsiTopologySupport = csiTopologySupport;
            IgnoreAz = ignoreAz;
            OverrideAz = overrideAz;
            Version = version;
        }
    }
}
