// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class ClusterNodeProblemDetector
    {
        public readonly string? CpuLimit;
        public readonly string? CpuRequest;
        public readonly bool? Enabled;
        public readonly string? Image;
        public readonly string? MemoryLimit;
        public readonly string? MemoryRequest;

        [OutputConstructor]
        private ClusterNodeProblemDetector(
            string? cpuLimit,

            string? cpuRequest,

            bool? enabled,

            string? image,

            string? memoryLimit,

            string? memoryRequest)
        {
            CpuLimit = cpuLimit;
            CpuRequest = cpuRequest;
            Enabled = enabled;
            Image = image;
            MemoryLimit = memoryLimit;
            MemoryRequest = memoryRequest;
        }
    }
}
