// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class ClusterKubeDnsAffinityPodAffinity
    {
        public readonly ImmutableArray<Outputs.ClusterKubeDnsAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution> PreferredDuringSchedulingIgnoredDuringExecutions;
        public readonly ImmutableArray<Outputs.ClusterKubeDnsAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecution> RequiredDuringSchedulingIgnoredDuringExecutions;

        [OutputConstructor]
        private ClusterKubeDnsAffinityPodAffinity(
            ImmutableArray<Outputs.ClusterKubeDnsAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution> preferredDuringSchedulingIgnoredDuringExecutions,

            ImmutableArray<Outputs.ClusterKubeDnsAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecution> requiredDuringSchedulingIgnoredDuringExecutions)
        {
            PreferredDuringSchedulingIgnoredDuringExecutions = preferredDuringSchedulingIgnoredDuringExecutions;
            RequiredDuringSchedulingIgnoredDuringExecutions = requiredDuringSchedulingIgnoredDuringExecutions;
        }
    }
}
