// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class ClusterApiLoadBalancerAccessLog
    {
        public readonly string? Bucket;
        public readonly string? BucketPrefix;
        public readonly int? Interval;

        [OutputConstructor]
        private ClusterApiLoadBalancerAccessLog(
            string? bucket,

            string? bucketPrefix,

            int? interval)
        {
            Bucket = bucket;
            BucketPrefix = bucketPrefix;
            Interval = interval;
        }
    }
}
