// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class ClusterNetworkingAmazonVpc
    {
        public readonly ImmutableArray<Outputs.ClusterNetworkingAmazonVpcEnv> Envs;
        public readonly string? Image;
        public readonly string? InitImage;

        [OutputConstructor]
        private ClusterNetworkingAmazonVpc(
            ImmutableArray<Outputs.ClusterNetworkingAmazonVpcEnv> envs,

            string? image,

            string? initImage)
        {
            Envs = envs;
            Image = image;
            InitImage = initImage;
        }
    }
}
