// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class ClusterNodeAuthorizationNodeAuthorizer
    {
        public readonly string? Authorizer;
        public readonly ImmutableArray<string> Features;
        public readonly string? Image;
        public readonly string? Interval;
        public readonly string? NodeUrl;
        public readonly int? Port;
        public readonly string? Timeout;
        public readonly string? TokenTtl;

        [OutputConstructor]
        private ClusterNodeAuthorizationNodeAuthorizer(
            string? authorizer,

            ImmutableArray<string> features,

            string? image,

            string? interval,

            string? nodeUrl,

            int? port,

            string? timeout,

            string? tokenTtl)
        {
            Authorizer = authorizer;
            Features = features;
            Image = image;
            Interval = interval;
            NodeUrl = nodeUrl;
            Port = port;
            Timeout = timeout;
            TokenTtl = tokenTtl;
        }
    }
}
