// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class ClusterCloudProvider
    {
        public readonly Outputs.ClusterCloudProviderAws? Aws;
        public readonly Outputs.ClusterCloudProviderAzure? Azure;
        public readonly Outputs.ClusterCloudProviderDo? Do;
        public readonly Outputs.ClusterCloudProviderGce? Gce;
        public readonly Outputs.ClusterCloudProviderHetzner? Hetzner;
        public readonly Outputs.ClusterCloudProviderOpenstack? Openstack;

        [OutputConstructor]
        private ClusterCloudProvider(
            Outputs.ClusterCloudProviderAws? aws,

            Outputs.ClusterCloudProviderAzure? azure,

            Outputs.ClusterCloudProviderDo? @do,

            Outputs.ClusterCloudProviderGce? gce,

            Outputs.ClusterCloudProviderHetzner? hetzner,

            Outputs.ClusterCloudProviderOpenstack? openstack)
        {
            Aws = aws;
            Azure = azure;
            Do = @do;
            Gce = gce;
            Hetzner = hetzner;
            Openstack = openstack;
        }
    }
}
