// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class ClusterTopology
    {
        public readonly Outputs.ClusterTopologyBastion? Bastion;
        public readonly Outputs.ClusterTopologyDns Dns;
        public readonly string Masters;
        public readonly string Nodes;

        [OutputConstructor]
        private ClusterTopology(
            Outputs.ClusterTopologyBastion? bastion,

            Outputs.ClusterTopologyDns dns,

            string masters,

            string nodes)
        {
            Bastion = bastion;
            Dns = dns;
            Masters = masters;
            Nodes = nodes;
        }
    }
}
