// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class ClusterNetworking
    {
        public readonly Outputs.ClusterNetworkingAmazonVpc? AmazonVpc;
        public readonly Outputs.ClusterNetworkingCalico? Calico;
        public readonly Outputs.ClusterNetworkingCanal? Canal;
        public readonly Outputs.ClusterNetworkingCilium? Cilium;
        public readonly Outputs.ClusterNetworkingClassic? Classic;
        public readonly Outputs.ClusterNetworkingCni? Cni;
        public readonly Outputs.ClusterNetworkingExternal? External;
        public readonly Outputs.ClusterNetworkingFlannel? Flannel;
        public readonly Outputs.ClusterNetworkingGce? Gce;
        public readonly Outputs.ClusterNetworkingKopeio? Kopeio;
        public readonly Outputs.ClusterNetworkingKubenet? Kubenet;
        public readonly Outputs.ClusterNetworkingKuberouter? Kuberouter;
        public readonly Outputs.ClusterNetworkingLyftVpc? LyftVpc;
        public readonly Outputs.ClusterNetworkingRomana? Romana;
        public readonly Outputs.ClusterNetworkingWeave? Weave;

        [OutputConstructor]
        private ClusterNetworking(
            Outputs.ClusterNetworkingAmazonVpc? amazonVpc,

            Outputs.ClusterNetworkingCalico? calico,

            Outputs.ClusterNetworkingCanal? canal,

            Outputs.ClusterNetworkingCilium? cilium,

            Outputs.ClusterNetworkingClassic? classic,

            Outputs.ClusterNetworkingCni? cni,

            Outputs.ClusterNetworkingExternal? external,

            Outputs.ClusterNetworkingFlannel? flannel,

            Outputs.ClusterNetworkingGce? gce,

            Outputs.ClusterNetworkingKopeio? kopeio,

            Outputs.ClusterNetworkingKubenet? kubenet,

            Outputs.ClusterNetworkingKuberouter? kuberouter,

            Outputs.ClusterNetworkingLyftVpc? lyftVpc,

            Outputs.ClusterNetworkingRomana? romana,

            Outputs.ClusterNetworkingWeave? weave)
        {
            AmazonVpc = amazonVpc;
            Calico = calico;
            Canal = canal;
            Cilium = cilium;
            Classic = classic;
            Cni = cni;
            External = external;
            Flannel = flannel;
            Gce = gce;
            Kopeio = kopeio;
            Kubenet = kubenet;
            Kuberouter = kuberouter;
            LyftVpc = lyftVpc;
            Romana = romana;
            Weave = weave;
        }
    }
}
