// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class ClusterAuthentication
    {
        public readonly Outputs.ClusterAuthenticationAws? Aws;
        public readonly Outputs.ClusterAuthenticationKopeio? Kopeio;

        [OutputConstructor]
        private ClusterAuthentication(
            Outputs.ClusterAuthenticationAws? aws,

            Outputs.ClusterAuthenticationKopeio? kopeio)
        {
            Aws = aws;
            Kopeio = kopeio;
        }
    }
}
