// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class ClusterNetworkingFlannel
    {
        public readonly string? Backend;
        public readonly int? IptablesResyncSeconds;

        [OutputConstructor]
        private ClusterNetworkingFlannel(
            string? backend,

            int? iptablesResyncSeconds)
        {
            Backend = backend;
            IptablesResyncSeconds = iptablesResyncSeconds;
        }
    }
}
