// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class GetClusterCloudProviderOpenstackNetworkResult
    {
        public readonly ImmutableArray<string> AvailabilityZoneHints;
        public readonly ImmutableArray<string> InternalNetworkNames;
        public readonly bool Ipv6SupportDisabled;
        public readonly ImmutableArray<string> PublicNetworkNames;

        [OutputConstructor]
        private GetClusterCloudProviderOpenstackNetworkResult(
            ImmutableArray<string> availabilityZoneHints,

            ImmutableArray<string> internalNetworkNames,

            bool ipv6SupportDisabled,

            ImmutableArray<string> publicNetworkNames)
        {
            AvailabilityZoneHints = availabilityZoneHints;
            InternalNetworkNames = internalNetworkNames;
            Ipv6SupportDisabled = ipv6SupportDisabled;
            PublicNetworkNames = publicNetworkNames;
        }
    }
}
