// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class GetClusterAwsLoadBalancerControllerResult
    {
        public readonly bool EnableShield;
        public readonly bool EnableWaFv2;
        public readonly bool EnableWaf;
        public readonly bool Enabled;
        public readonly string Version;

        [OutputConstructor]
        private GetClusterAwsLoadBalancerControllerResult(
            bool enableShield,

            bool enableWaFv2,

            bool enableWaf,

            bool enabled,

            string version)
        {
            EnableShield = enableShield;
            EnableWaFv2 = enableWaFv2;
            EnableWaf = enableWaf;
            Enabled = enabled;
            Version = version;
        }
    }
}
