// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class GetClusterPodIdentityWebhookResult
    {
        public readonly bool Enabled;
        public readonly int Replicas;

        [OutputConstructor]
        private GetClusterPodIdentityWebhookResult(
            bool enabled,

            int replicas)
        {
            Enabled = enabled;
            Replicas = replicas;
        }
    }
}
