// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class GetClusterExternalDnResult
    {
        public readonly string Provider;
        public readonly bool WatchIngress;
        public readonly string WatchNamespace;

        [OutputConstructor]
        private GetClusterExternalDnResult(
            string provider,

            bool watchIngress,

            string watchNamespace)
        {
            Provider = provider;
            WatchIngress = watchIngress;
            WatchNamespace = watchNamespace;
        }
    }
}
