// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class GetClusterMetricsServerResult
    {
        public readonly bool Enabled;
        public readonly string Image;
        public readonly bool Insecure;

        [OutputConstructor]
        private GetClusterMetricsServerResult(
            bool enabled,

            string image,

            bool insecure)
        {
            Enabled = enabled;
            Image = image;
            Insecure = insecure;
        }
    }
}
