// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class GetClusterHookResult
    {
        public readonly ImmutableArray<string> Befores;
        public readonly bool Enabled;
        public readonly ImmutableArray<Outputs.GetClusterHookExecContainerResult> ExecContainers;
        public readonly string Manifest;
        /// <summary>
        /// - String - Name defines the cluster name.
        /// </summary>
        public readonly string Name;
        public readonly ImmutableArray<string> Requires;
        public readonly ImmutableArray<string> Roles;
        public readonly bool UseRawManifest;

        [OutputConstructor]
        private GetClusterHookResult(
            ImmutableArray<string> befores,

            bool enabled,

            ImmutableArray<Outputs.GetClusterHookExecContainerResult> execContainers,

            string manifest,

            string name,

            ImmutableArray<string> requires,

            ImmutableArray<string> roles,

            bool useRawManifest)
        {
            Befores = befores;
            Enabled = enabled;
            ExecContainers = execContainers;
            Manifest = manifest;
            Name = name;
            Requires = requires;
            Roles = roles;
            UseRawManifest = useRawManifest;
        }
    }
}
