// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class GetClusterEtcdClusterManagerResult
    {
        public readonly string BackupInterval;
        public readonly string DiscoveryPollInterval;
        public readonly ImmutableArray<Outputs.GetClusterEtcdClusterManagerEnvResult> Envs;
        public readonly string Image;
        public readonly int LogLevel;

        [OutputConstructor]
        private GetClusterEtcdClusterManagerResult(
            string backupInterval,

            string discoveryPollInterval,

            ImmutableArray<Outputs.GetClusterEtcdClusterManagerEnvResult> envs,

            string image,

            int logLevel)
        {
            BackupInterval = backupInterval;
            DiscoveryPollInterval = discoveryPollInterval;
            Envs = envs;
            Image = image;
            LogLevel = logLevel;
        }
    }
}
