// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class GetClusterNetworkingCiliaHubbleResult
    {
        public readonly bool Enabled;
        public readonly ImmutableArray<string> Metrics;

        [OutputConstructor]
        private GetClusterNetworkingCiliaHubbleResult(
            bool enabled,

            ImmutableArray<string> metrics)
        {
            Enabled = enabled;
            Metrics = metrics;
        }
    }
}
