// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class GetClusterSubnetResult
    {
        public readonly ImmutableArray<Outputs.GetClusterSubnetAdditionalRouteResult> AdditionalRoutes;
        public readonly string Cidr;
        public readonly string Egress;
        public readonly string Ipv6Cidr;
        /// <summary>
        /// - String - Name defines the cluster name.
        /// </summary>
        public readonly string Name;
        public readonly string ProviderId;
        public readonly string PublicIp;
        public readonly string Region;
        public readonly string Type;
        public readonly string Zone;

        [OutputConstructor]
        private GetClusterSubnetResult(
            ImmutableArray<Outputs.GetClusterSubnetAdditionalRouteResult> additionalRoutes,

            string cidr,

            string egress,

            string ipv6Cidr,

            string name,

            string providerId,

            string publicIp,

            string region,

            string type,

            string zone)
        {
            AdditionalRoutes = additionalRoutes;
            Cidr = cidr;
            Egress = egress;
            Ipv6Cidr = ipv6Cidr;
            Name = name;
            ProviderId = providerId;
            PublicIp = publicIp;
            Region = region;
            Type = type;
            Zone = zone;
        }
    }
}
