// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class GetInstanceGroupMixedInstancesPolicyInstanceRequirementMemoryResult
    {
        public readonly string Max;
        public readonly string Min;

        [OutputConstructor]
        private GetInstanceGroupMixedInstancesPolicyInstanceRequirementMemoryResult(
            string max,

            string min)
        {
            Max = max;
            Min = min;
        }
    }
}
