// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class InstanceGroupContainerdRunc
    {
        /// <summary>
        /// - List(String) - Packages specifies additional packages to be installed.
        /// </summary>
        public readonly Outputs.InstanceGroupContainerdRuncPackages? Packages;
        public readonly string? Version;

        [OutputConstructor]
        private InstanceGroupContainerdRunc(
            Outputs.InstanceGroupContainerdRuncPackages? packages,

            string? version)
        {
            Packages = packages;
            Version = version;
        }
    }
}
