// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class InstanceGroupInstanceMetadata
    {
        public readonly int? HttpPutResponseHopLimit;
        public readonly string? HttpTokens;

        [OutputConstructor]
        private InstanceGroupInstanceMetadata(
            int? httpPutResponseHopLimit,

            string? httpTokens)
        {
            HttpPutResponseHopLimit = httpPutResponseHopLimit;
            HttpTokens = httpTokens;
        }
    }
}
