// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Outputs
{

    [OutputType]
    public sealed class InstanceGroupMixedInstancesPolicyInstanceRequirements
    {
        public readonly Outputs.InstanceGroupMixedInstancesPolicyInstanceRequirementsCpu? Cpu;
        public readonly Outputs.InstanceGroupMixedInstancesPolicyInstanceRequirementsMemory? Memory;

        [OutputConstructor]
        private InstanceGroupMixedInstancesPolicyInstanceRequirements(
            Outputs.InstanceGroupMixedInstancesPolicyInstanceRequirementsCpu? cpu,

            Outputs.InstanceGroupMixedInstancesPolicyInstanceRequirementsMemory? memory)
        {
            Cpu = cpu;
            Memory = memory;
        }
    }
}
