// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterNetworkingArgs : global::Pulumi.ResourceArgs
    {
        [Input("amazonVpc")]
        public Input<Inputs.ClusterNetworkingAmazonVpcArgs>? AmazonVpc { get; set; }

        [Input("calico")]
        public Input<Inputs.ClusterNetworkingCalicoArgs>? Calico { get; set; }

        [Input("canal")]
        public Input<Inputs.ClusterNetworkingCanalArgs>? Canal { get; set; }

        [Input("cilium")]
        public Input<Inputs.ClusterNetworkingCiliumArgs>? Cilium { get; set; }

        [Input("classic")]
        public Input<Inputs.ClusterNetworkingClassicArgs>? Classic { get; set; }

        [Input("cni")]
        public Input<Inputs.ClusterNetworkingCniArgs>? Cni { get; set; }

        [Input("external")]
        public Input<Inputs.ClusterNetworkingExternalArgs>? External { get; set; }

        [Input("flannel")]
        public Input<Inputs.ClusterNetworkingFlannelArgs>? Flannel { get; set; }

        [Input("gce")]
        public Input<Inputs.ClusterNetworkingGceArgs>? Gce { get; set; }

        [Input("kopeio")]
        public Input<Inputs.ClusterNetworkingKopeioArgs>? Kopeio { get; set; }

        [Input("kubenet")]
        public Input<Inputs.ClusterNetworkingKubenetArgs>? Kubenet { get; set; }

        [Input("kuberouter")]
        public Input<Inputs.ClusterNetworkingKuberouterArgs>? Kuberouter { get; set; }

        [Input("lyftVpc")]
        public Input<Inputs.ClusterNetworkingLyftVpcArgs>? LyftVpc { get; set; }

        [Input("romana")]
        public Input<Inputs.ClusterNetworkingRomanaArgs>? Romana { get; set; }

        [Input("weave")]
        public Input<Inputs.ClusterNetworkingWeaveArgs>? Weave { get; set; }

        public ClusterNetworkingArgs()
        {
        }
        public static new ClusterNetworkingArgs Empty => new ClusterNetworkingArgs();
    }
}
