// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterKubeDnsAffinityPodAntiAffinityGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("preferredDuringSchedulingIgnoredDuringExecutions")]
        private InputList<Inputs.ClusterKubeDnsAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionGetArgs>? _preferredDuringSchedulingIgnoredDuringExecutions;
        public InputList<Inputs.ClusterKubeDnsAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionGetArgs> PreferredDuringSchedulingIgnoredDuringExecutions
        {
            get => _preferredDuringSchedulingIgnoredDuringExecutions ?? (_preferredDuringSchedulingIgnoredDuringExecutions = new InputList<Inputs.ClusterKubeDnsAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionGetArgs>());
            set => _preferredDuringSchedulingIgnoredDuringExecutions = value;
        }

        [Input("requiredDuringSchedulingIgnoredDuringExecutions")]
        private InputList<Inputs.ClusterKubeDnsAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionGetArgs>? _requiredDuringSchedulingIgnoredDuringExecutions;
        public InputList<Inputs.ClusterKubeDnsAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionGetArgs> RequiredDuringSchedulingIgnoredDuringExecutions
        {
            get => _requiredDuringSchedulingIgnoredDuringExecutions ?? (_requiredDuringSchedulingIgnoredDuringExecutions = new InputList<Inputs.ClusterKubeDnsAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionGetArgs>());
            set => _requiredDuringSchedulingIgnoredDuringExecutions = value;
        }

        public ClusterKubeDnsAffinityPodAntiAffinityGetArgs()
        {
        }
        public static new ClusterKubeDnsAffinityPodAntiAffinityGetArgs Empty => new ClusterKubeDnsAffinityPodAntiAffinityGetArgs();
    }
}
