// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterAuthenticationArgs : global::Pulumi.ResourceArgs
    {
        [Input("aws")]
        public Input<Inputs.ClusterAuthenticationAwsArgs>? Aws { get; set; }

        [Input("kopeio")]
        public Input<Inputs.ClusterAuthenticationKopeioArgs>? Kopeio { get; set; }

        public ClusterAuthenticationArgs()
        {
        }
        public static new ClusterAuthenticationArgs Empty => new ClusterAuthenticationArgs();
    }
}
