// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterCloudProviderOpenstackRouterArgs : global::Pulumi.ResourceArgs
    {
        [Input("availabilityZoneHints")]
        private InputList<string>? _availabilityZoneHints;
        public InputList<string> AvailabilityZoneHints
        {
            get => _availabilityZoneHints ?? (_availabilityZoneHints = new InputList<string>());
            set => _availabilityZoneHints = value;
        }

        [Input("dnsServers")]
        public Input<string>? DnsServers { get; set; }

        [Input("externalNetwork")]
        public Input<string>? ExternalNetwork { get; set; }

        [Input("externalSubnet")]
        public Input<string>? ExternalSubnet { get; set; }

        public ClusterCloudProviderOpenstackRouterArgs()
        {
        }
        public static new ClusterCloudProviderOpenstackRouterArgs Empty => new ClusterCloudProviderOpenstackRouterArgs();
    }
}
