// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterEtcdClusterManagerGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("backupInterval")]
        public Input<string>? BackupInterval { get; set; }

        [Input("discoveryPollInterval")]
        public Input<string>? DiscoveryPollInterval { get; set; }

        [Input("envs")]
        private InputList<Inputs.ClusterEtcdClusterManagerEnvGetArgs>? _envs;
        public InputList<Inputs.ClusterEtcdClusterManagerEnvGetArgs> Envs
        {
            get => _envs ?? (_envs = new InputList<Inputs.ClusterEtcdClusterManagerEnvGetArgs>());
            set => _envs = value;
        }

        [Input("image")]
        public Input<string>? Image { get; set; }

        [Input("logLevel")]
        public Input<int>? LogLevel { get; set; }

        public ClusterEtcdClusterManagerGetArgs()
        {
        }
        public static new ClusterEtcdClusterManagerGetArgs Empty => new ClusterEtcdClusterManagerGetArgs();
    }
}
