// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterAwsLoadBalancerControllerArgs : global::Pulumi.ResourceArgs
    {
        [Input("enableShield")]
        public Input<bool>? EnableShield { get; set; }

        [Input("enableWaFv2")]
        public Input<bool>? EnableWaFv2 { get; set; }

        [Input("enableWaf")]
        public Input<bool>? EnableWaf { get; set; }

        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("version")]
        public Input<string>? Version { get; set; }

        public ClusterAwsLoadBalancerControllerArgs()
        {
        }
        public static new ClusterAwsLoadBalancerControllerArgs Empty => new ClusterAwsLoadBalancerControllerArgs();
    }
}
