// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterCloudConfigAwsEbsCsiDriverArgs : global::Pulumi.ResourceArgs
    {
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("managed")]
        public Input<bool>? Managed { get; set; }

        [Input("podAnnotations")]
        private InputMap<string>? _podAnnotations;
        public InputMap<string> PodAnnotations
        {
            get => _podAnnotations ?? (_podAnnotations = new InputMap<string>());
            set => _podAnnotations = value;
        }

        [Input("version")]
        public Input<string>? Version { get; set; }

        [Input("volumeAttachLimit")]
        public Input<int>? VolumeAttachLimit { get; set; }

        public ClusterCloudConfigAwsEbsCsiDriverArgs()
        {
        }
        public static new ClusterCloudConfigAwsEbsCsiDriverArgs Empty => new ClusterCloudConfigAwsEbsCsiDriverArgs();
    }
}
