// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterCloudProviderOpenstackGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("blockStorage")]
        public Input<Inputs.ClusterCloudProviderOpenstackBlockStorageGetArgs>? BlockStorage { get; set; }

        [Input("insecureSkipVerify")]
        public Input<bool>? InsecureSkipVerify { get; set; }

        [Input("loadbalancer")]
        public Input<Inputs.ClusterCloudProviderOpenstackLoadbalancerGetArgs>? Loadbalancer { get; set; }

        [Input("metadata")]
        public Input<Inputs.ClusterCloudProviderOpenstackMetadataGetArgs>? Metadata { get; set; }

        [Input("monitor")]
        public Input<Inputs.ClusterCloudProviderOpenstackMonitorGetArgs>? Monitor { get; set; }

        [Input("network")]
        public Input<Inputs.ClusterCloudProviderOpenstackNetworkGetArgs>? Network { get; set; }

        [Input("router")]
        public Input<Inputs.ClusterCloudProviderOpenstackRouterGetArgs>? Router { get; set; }

        public ClusterCloudProviderOpenstackGetArgs()
        {
        }
        public static new ClusterCloudProviderOpenstackGetArgs Empty => new ClusterCloudProviderOpenstackGetArgs();
    }
}
