// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterKubeDnsAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("labelSelector")]
        public Input<Inputs.ClusterKubeDnsAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelectorGetArgs>? LabelSelector { get; set; }

        [Input("namespaceSelector")]
        public Input<Inputs.ClusterKubeDnsAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionNamespaceSelectorGetArgs>? NamespaceSelector { get; set; }

        [Input("namespaces")]
        private InputList<string>? _namespaces;
        public InputList<string> Namespaces
        {
            get => _namespaces ?? (_namespaces = new InputList<string>());
            set => _namespaces = value;
        }

        [Input("topologyKey")]
        public Input<string>? TopologyKey { get; set; }

        public ClusterKubeDnsAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionGetArgs()
        {
        }
        public static new ClusterKubeDnsAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionGetArgs Empty => new ClusterKubeDnsAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionGetArgs();
    }
}
