// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterAuthenticationAwsArgs : global::Pulumi.ResourceArgs
    {
        [Input("backendMode")]
        public Input<string>? BackendMode { get; set; }

        [Input("clusterId")]
        public Input<string>? ClusterId { get; set; }

        [Input("cpuLimit")]
        public Input<string>? CpuLimit { get; set; }

        [Input("cpuRequest")]
        public Input<string>? CpuRequest { get; set; }

        [Input("identityMappings")]
        private InputList<Inputs.ClusterAuthenticationAwsIdentityMappingArgs>? _identityMappings;
        public InputList<Inputs.ClusterAuthenticationAwsIdentityMappingArgs> IdentityMappings
        {
            get => _identityMappings ?? (_identityMappings = new InputList<Inputs.ClusterAuthenticationAwsIdentityMappingArgs>());
            set => _identityMappings = value;
        }

        [Input("image")]
        public Input<string>? Image { get; set; }

        [Input("memoryLimit")]
        public Input<string>? MemoryLimit { get; set; }

        [Input("memoryRequest")]
        public Input<string>? MemoryRequest { get; set; }

        public ClusterAuthenticationAwsArgs()
        {
        }
        public static new ClusterAuthenticationAwsArgs Empty => new ClusterAuthenticationAwsArgs();
    }
}
