// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterNodeAuthorizationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("nodeAuthorizer")]
        public Input<Inputs.ClusterNodeAuthorizationNodeAuthorizerGetArgs>? NodeAuthorizer { get; set; }

        public ClusterNodeAuthorizationGetArgs()
        {
        }
        public static new ClusterNodeAuthorizationGetArgs Empty => new ClusterNodeAuthorizationGetArgs();
    }
}
