// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterCloudProviderOpenstackNetworkArgs : global::Pulumi.ResourceArgs
    {
        [Input("availabilityZoneHints")]
        private InputList<string>? _availabilityZoneHints;
        public InputList<string> AvailabilityZoneHints
        {
            get => _availabilityZoneHints ?? (_availabilityZoneHints = new InputList<string>());
            set => _availabilityZoneHints = value;
        }

        [Input("internalNetworkNames")]
        private InputList<string>? _internalNetworkNames;
        public InputList<string> InternalNetworkNames
        {
            get => _internalNetworkNames ?? (_internalNetworkNames = new InputList<string>());
            set => _internalNetworkNames = value;
        }

        [Input("ipv6SupportDisabled")]
        public Input<bool>? Ipv6SupportDisabled { get; set; }

        [Input("publicNetworkNames")]
        private InputList<string>? _publicNetworkNames;
        public InputList<string> PublicNetworkNames
        {
            get => _publicNetworkNames ?? (_publicNetworkNames = new InputList<string>());
            set => _publicNetworkNames = value;
        }

        public ClusterCloudProviderOpenstackNetworkArgs()
        {
        }
        public static new ClusterCloudProviderOpenstackNetworkArgs Empty => new ClusterCloudProviderOpenstackNetworkArgs();
    }
}
