// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterApiGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("dns")]
        public Input<Inputs.ClusterApiDnsGetArgs>? Dns { get; set; }

        [Input("loadBalancer")]
        public Input<Inputs.ClusterApiLoadBalancerGetArgs>? LoadBalancer { get; set; }

        public ClusterApiGetArgs()
        {
        }
        public static new ClusterApiGetArgs Empty => new ClusterApiGetArgs();
    }
}
