// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterIamServiceAccountExternalPermissionAwsArgs : global::Pulumi.ResourceArgs
    {
        [Input("inlinePolicy")]
        public Input<string>? InlinePolicy { get; set; }

        [Input("policyArNs")]
        private InputList<string>? _policyArNs;
        public InputList<string> PolicyArNs
        {
            get => _policyArNs ?? (_policyArNs = new InputList<string>());
            set => _policyArNs = value;
        }

        public ClusterIamServiceAccountExternalPermissionAwsArgs()
        {
        }
        public static new ClusterIamServiceAccountExternalPermissionAwsArgs Empty => new ClusterIamServiceAccountExternalPermissionAwsArgs();
    }
}
