// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterAssetsArgs : global::Pulumi.ResourceArgs
    {
        [Input("containerProxy")]
        public Input<string>? ContainerProxy { get; set; }

        [Input("containerRegistry")]
        public Input<string>? ContainerRegistry { get; set; }

        [Input("fileRepository")]
        public Input<string>? FileRepository { get; set; }

        public ClusterAssetsArgs()
        {
        }
        public static new ClusterAssetsArgs Empty => new ClusterAssetsArgs();
    }
}
