// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class ClusterExternalDnsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("provider")]
        public Input<string>? Provider { get; set; }

        [Input("watchIngress")]
        public Input<bool>? WatchIngress { get; set; }

        [Input("watchNamespace")]
        public Input<string>? WatchNamespace { get; set; }

        public ClusterExternalDnsGetArgs()
        {
        }
        public static new ClusterExternalDnsGetArgs Empty => new ClusterExternalDnsGetArgs();
    }
}
