// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class InstanceGroupRollingUpdateGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("drainAndTerminate")]
        public Input<bool>? DrainAndTerminate { get; set; }

        [Input("maxSurge")]
        public Input<string>? MaxSurge { get; set; }

        [Input("maxUnavailable")]
        public Input<string>? MaxUnavailable { get; set; }

        public InstanceGroupRollingUpdateGetArgs()
        {
        }
        public static new InstanceGroupRollingUpdateGetArgs Empty => new InstanceGroupRollingUpdateGetArgs();
    }
}
