// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class InstanceGroupMixedInstancesPolicyGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("instanceRequirements")]
        public Input<Inputs.InstanceGroupMixedInstancesPolicyInstanceRequirementsGetArgs>? InstanceRequirements { get; set; }

        [Input("instances")]
        private InputList<string>? _instances;
        public InputList<string> Instances
        {
            get => _instances ?? (_instances = new InputList<string>());
            set => _instances = value;
        }

        [Input("onDemandAboveBase")]
        public Input<Inputs.InstanceGroupMixedInstancesPolicyOnDemandAboveBaseGetArgs>? OnDemandAboveBase { get; set; }

        [Input("onDemandAllocationStrategy")]
        public Input<string>? OnDemandAllocationStrategy { get; set; }

        [Input("onDemandBase")]
        public Input<Inputs.InstanceGroupMixedInstancesPolicyOnDemandBaseGetArgs>? OnDemandBase { get; set; }

        [Input("spotAllocationStrategy")]
        public Input<string>? SpotAllocationStrategy { get; set; }

        [Input("spotInstancePools")]
        public Input<int>? SpotInstancePools { get; set; }

        public InstanceGroupMixedInstancesPolicyGetArgs()
        {
        }
        public static new InstanceGroupMixedInstancesPolicyGetArgs Empty => new InstanceGroupMixedInstancesPolicyGetArgs();
    }
}
