// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kops.Inputs
{

    public sealed class InstanceGroupGuestAcceleratorGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("acceleratorCount")]
        public Input<int>? AcceleratorCount { get; set; }

        [Input("acceleratorType")]
        public Input<string>? AcceleratorType { get; set; }

        public InstanceGroupGuestAcceleratorGetArgs()
        {
        }
        public static new InstanceGroupGuestAcceleratorGetArgs Empty => new InstanceGroupGuestAcceleratorGetArgs();
    }
}
